replicaCount: 1

image:
  repository: ghcr.io/bezerker/goatgram
  tag: "adfe7ad"
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: cloudflare-tunnel
  annotations:
    strrl.dev/cloudflare-tunnel-ingress-controller: enabled
  hosts:
    - host: goatgram.net
      paths:
        - path: /
          pathType: Prefix
    - host: www.goatgram.net
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
